var w=c.width=window.innerWidth,h=c.height=window.innerHeight,ctx=c.getContext('2d'),opts={len:20,count:50,baseTime:10,addedTime:10,dieChance:.05,spawnChance:1,sparkChance:.1,sparkDist:10,sparkSize:2,color:'hsl(hue,100%,light%)',baseLight:50,addedLight:10,shadowToTimePropMult:6,baseLightInputMultiplier:.01,addedLightInputMultiplier:.02,cx:w/2,cy:h/2,repaintAlpha:.04,hueChange:.1},tick=0,lines=[],dieX=w/2/opts.len,dieY=h/2/opts.len,baseRad=Math.PI*2/6;ctx.fillStyle='black';ctx.fillRect(0,0,w,h);function loop(){window.requestAnimationFrame(loop);++tick;ctx.globalCompositeOperation='source-over';ctx.shadowBlur=0;ctx.fillStyle='rgba(0,0,0,alp)'.replace('alp',opts.repaintAlpha);ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='lighter';if(lines.length<opts.count&&Math.random()<opts.spawnChance)lines.push(new Line);lines.map(function(line){line.step()})}
function Line(){this.reset()}
Line.prototype.reset=function(){this.x=0;this.y=0;this.addedX=0;this.addedY=0;this.rad=0;this.lightInputMultiplier=opts.baseLightInputMultiplier+opts.addedLightInputMultiplier*Math.random();this.color=opts.color.replace('hue',tick*opts.hueChange);this.cumulativeTime=0;this.beginPhase()}
Line.prototype.beginPhase=function(){this.x+=this.addedX;this.y+=this.addedY;this.time=0;this.targetTime=(opts.baseTime+opts.addedTime*Math.random())|0;this.rad+=baseRad*(Math.random()<.5?1:-1);this.addedX=Math.cos(this.rad);this.addedY=Math.sin(this.rad);if(Math.random()<opts.dieChance||this.x>dieX||this.x<-dieX||this.y>dieY||this.y<-dieY)this.reset()}
Line.prototype.step=function(){++this.time;++this.cumulativeTime;if(this.time>=this.targetTime)this.beginPhase();var prop=this.time/this.targetTime,wave=Math.sin(prop*Math.PI/2),x=this.addedX*wave,y=this.addedY*wave;ctx.shadowBlur=prop*opts.shadowToTimePropMult;ctx.fillStyle=ctx.shadowColor=this.color.replace('light',opts.baseLight+opts.addedLight*Math.sin(this.cumulativeTime*this.lightInputMultiplier));ctx.fillRect(opts.cx+(this.x+x)*opts.len,opts.cy+(this.y+y)*opts.len,2,2);if(Math.random()<opts.sparkChance)ctx.fillRect(opts.cx+(this.x+x)*opts.len+Math.random()*opts.sparkDist*(Math.random()<.5?1:-1)-opts.sparkSize/2,opts.cy+(this.y+y)*opts.len+Math.random()*opts.sparkDist*(Math.random()<.5?1:-1)-opts.sparkSize/2,opts.sparkSize,opts.sparkSize)}
loop();window.addEventListener('resize',function(){w=c.width=window.innerWidth;h=c.height=window.innerHeight;ctx.fillStyle='black';ctx.fillRect(0,0,w,h);opts.cx=w/2;opts.cy=h/2;dieX=w/2/opts.len;dieY=h/2/opts.len});var canvas=document.getElementById('canvas'),ctx1=canvas.getContext('2d'),w=canvas.width=window.innerWidth,h=canvas.height=window.innerHeight,hue=217,stars=[],count=0,maxStars=1400;var canvas2=document.createElement('canvas'),ctx2=canvas2.getContext('2d');canvas2.width=100;canvas2.height=100;var half=canvas2.width/2,gradient2=ctx2.createRadialGradient(half,half,0,half,half,half);gradient2.addColorStop(0.025,'#fff');gradient2.addColorStop(0.1,'hsl('+hue+', 61%, 33%)');gradient2.addColorStop(0.25,'hsl('+hue+', 64%, 6%)');gradient2.addColorStop(1,'transparent');ctx2.fillStyle=gradient2;ctx2.beginPath();ctx2.arc(half,half,half,0,Math.PI*2);ctx2.fill();function random(min,max){if(arguments.length<2){max=min;min=0;}
if(min>max){var hold=max;max=min;min=hold;}
return Math.floor(Math.random()*(max-min+1))+min;}
var Star=function(){this.orbitRadius=random(w/2-50);this.radius=random(100,this.orbitRadius)/10;this.orbitX=w/2;this.orbitY=h/2;this.timePassed=random(0,maxStars);this.speed=random(this.orbitRadius)/900000;this.alpha=random(2,10)/10;count++;stars[count]=this;}
Star.prototype.draw=function(){var x=Math.sin(this.timePassed+1)*this.orbitRadius+this.orbitX,y=Math.cos(this.timePassed)*this.orbitRadius/2+this.orbitY,twinkle=random(10);if(twinkle===1&&this.alpha>0){this.alpha-=0.05;}else if(twinkle===2&&this.alpha<1){this.alpha+=0.05;}
ctx1.globalAlpha=this.alpha;ctx1.drawImage(canvas2,x-this.radius/2,y-this.radius/2,this.radius,this.radius);this.timePassed+=this.speed;}
for(var i=0;i<maxStars;i++){new Star();}
function animation(){ctx1.globalCompositeOperation='source-over';ctx1.globalAlpha=0.8;ctx1.fillStyle='hsla('+hue+', 64%, 6%, 1)';ctx1.fillRect(0,0,w,h)
ctx1.globalCompositeOperation='lighter';for(var i=1,l=stars.length;i<l;i++){stars[i].draw();};window.requestAnimationFrame(animation);}
animation();$(function(){var canvas5=document.getElementById("canvas5"),ctx5=canvas5.getContext('2d');canvas5.width=window.innerWidth;canvas5.height=window.innerHeight;ctx5.lineWidth=.3;ctx5.strokeStyle=(new Color(150)).style;var mousePosition={x:30*canvas5.width/100,y:30*canvas5.height/100};var dots={nb:750,distance:50,d_radius:100,array:[]};function colorValue(min){return Math.floor(Math.random()*255+min);}
function createColorStyle(r,g,b){return'rgba('+r+','+g+','+b+', 0.8)';}
function mixComponents(comp1,weight1,comp2,weight2){return(comp1*weight1+comp2*weight2)/(weight1+weight2);}
function averageColorStyles(dot1,dot2){var color1=dot1.color,color2=dot2.color;var r=mixComponents(color1.r,dot1.radius,color2.r,dot2.radius),g=mixComponents(color1.g,dot1.radius,color2.g,dot2.radius),b=mixComponents(color1.b,dot1.radius,color2.b,dot2.radius);return createColorStyle(Math.floor(r),Math.floor(g),Math.floor(b));}
function Color(min){min=min||0;this.r=colorValue(min);this.g=colorValue(min);this.b=colorValue(min);this.style=createColorStyle(this.r,this.g,this.b);}
function Dot(){this.x=Math.random()*canvas5.width;this.y=Math.random()*canvas5.height;this.vx=-.5+Math.random();this.vy=-.5+Math.random();this.radius=Math.random()*2;this.color=new Color();}
Dot.prototype={draw:function(){ctx5.beginPath();ctx5.fillStyle=this.color.style;ctx5.arc(this.x,this.y,this.radius,0,Math.PI*2,false);ctx5.fill();}};function createDots(){for(i=0;i<dots.nb;i++){dots.array.push(new Dot());}}
function moveDots(){for(i=0;i<dots.nb;i++){var dot=dots.array[i];if(dot.y<0||dot.y>canvas5.height){dot.vx=dot.vx;dot.vy=-dot.vy;}
else if(dot.x<0||dot.x>canvas5.width){dot.vx=-dot.vx;dot.vy=dot.vy;}
dot.x+=dot.vx;dot.y+=dot.vy;}}
function connectDots(){for(i=0;i<dots.nb;i++){for(j=0;j<dots.nb;j++){i_dot=dots.array[i];j_dot=dots.array[j];if((i_dot.x-j_dot.x)<dots.distance&&(i_dot.y-j_dot.y)<dots.distance&&(i_dot.x-j_dot.x)>-dots.distance&&(i_dot.y-j_dot.y)>-dots.distance){if((i_dot.x-mousePosition.x)<dots.d_radius&&(i_dot.y-mousePosition.y)<dots.d_radius&&(i_dot.x-mousePosition.x)>-dots.d_radius&&(i_dot.y-mousePosition.y)>-dots.d_radius){ctx5.beginPath();ctx5.strokeStyle=averageColorStyles(i_dot,j_dot);ctx5.moveTo(i_dot.x,i_dot.y);ctx5.lineTo(j_dot.x,j_dot.y);ctx5.stroke();ctx5.closePath();}}}}}
function drawDots(){for(i=0;i<dots.nb;i++){var dot=dots.array[i];dot.draw();}}
function animateDots(){ctx5.clearRect(0,0,canvas5.width,canvas5.height);moveDots();connectDots();drawDots();requestAnimationFrame(animateDots);}
$('canvas5').on('mousemove',function(e){mousePosition.x=e.pageX;mousePosition.y=e.pageY;});$('canvas5').on('mouseleave',function(e){mousePosition.x=canvas5.width/2;mousePosition.y=canvas5.height/2;});createDots();requestAnimationFrame(animateDots);});